# Generated by Django 3.1.7 on 2021-05-29 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210529_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='tries',
            new_name='points',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='id_question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('id_user', 'id_question')},
        ),
        migrations.AlterIndexTogether(
            name='useranswer',
            index_together={('id_user', 'id_question')},
        ),
    ]
