# Generated by Django 3.1.7 on 2021-05-29 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210529_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id_game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='id_game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='id_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
        migrations.AlterIndexTogether(
            name='useranswer',
            index_together={('user', 'question')},
        ),
    ]
