# Generated by Django 3.2.3 on 2021-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210603_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='radius',
            field=models.IntegerField(default=20),
        ),
    ]
